### ISSUE TITLE
Rme Program-level DQ Report Results Outside of Date Range

### ISSUE THREAD

**Issue by entomacy** [COHHIO/RminorElevated#18]
*Rme Program-level DQ Report Results Outside of Date Range* 
Ticket*:* <https://hmis.cohhio.org/admin?pg=request&amp;reqid=34343>

[Slack Message](https://ohiobalanceofstatecoc.slack.com/archives/C03BZ3878UU/p1727203793890549)

**Comment by trevinflick** [comment]
b65d6e868796c86eb8614d5292c7bccb97617868 should fix this issue
