### ISSUE TITLE
Mahoning - Help Network - PATH - Services Only Omitted From Data Timeliness Report

### ISSUE THREAD

**Issue by entomacy** [COHHIO/RminorElevated#19]
I'm not seeing *Mahoning - Help Network - PATH - Services Only* in the data timeliness report in Rme.

[Slack Message](https://ohiobalanceofstatecoc.slack.com/archives/C03BZ3878UU/p1727290526347179?thread_ts=1727290526.347179&cid=C03BZ3878UU)

**Comment by trevinflick** [comment]
f288edbff1f5aa24b96e4544de35a35f7437ba9c fixes this
